### PR TITLE
Login form + Register UX + Refactor

### LINKED ISSUE #12: Add UX for form submits
The registration form is just a static form ATM, we should add loading/success/failed behaviors

### PR DESCRIPTION
**Pull request by AndreasPB**
* Renamed a bunch of stuff
* New login form
* Added UX to the register form
* Some extra st0ff

### CODE REVIEW

File: web/src/stores/jwt.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+// import { persist, sessionStorage } from "@macfja/svelte-persistent-store"
```
Comment (Pankai222) [inline web/src/stores/jwt.ts]: Remove unused import? If we're not gonna make use of sessionstorage, then the default svelte-store should be fine

**Review by Pankai222 — APPROVED** [review]

File: web/src/stores/jwt.ts (hunk 1 above)
Comment (AndreasPB) [reply web/src/stores/jwt.ts]: Done!
